const
      Enter = #13; Tab = #9; BS = #8;
      Esc   = #27; Space = #32; SH_Tab = #15;
      Rt = #77; Lf = #75;
      Up = #72; Dn = #80;
      PgUp = #73; PgDn = #81;
      Ins = #82; Del = #83; Home = #71; EndK = #79;
      F1 = #59; F2 = #60; F3 = #61; F4 = #62; F5 = #63;
      F6 = #64; F7 = #65; F8 = #66; F9 = #67; F10 = #68;
      F11 = #133; F12= #134;
      ALT_Q = #16; ALT_W = #17; ALT_E = #18; ALT_R = #19;
      ALT_T = #20; ALT_Y = #21; ALT_U = #22; ALT_I = #23;
      ALT_O = #24; ALT_P = #25; ALT_A = #30; ALT_S = #31;
      ALT_D = #32; ALT_F = #33; ALT_G = #34; ALT_H = #35;
      ALT_J = #36; ALT_K = #37; ALT_L = #38; ALT_Z = #44;
      ALT_X = #45; ALT_C = #46; ALT_V = #47; ALT_B = #48;
      ALT_N = #49; ALT_M = #50; ALT_SP = #2;