Hello, All!

‚®в. ќв  ивгЄ  Ўл«  ­ ЇЁб ­  Ј®¤  3 ­ § ¤ Ё § ­Ё¬ Ґвбп бЁ¬ў®«м­л¬
¤ЁддҐаҐ­жЁа®ў ­ЁҐ¬ (в® ЎЁим, ­  ўе®¤Ґ 'sin(x*x)' => ­  ўле®¤Ґ '2*x*cos(x*x)' Ё
в.¤.). ‚а®¤Ґ, ¤®ў®«м­® nice, ­Ґб¬®вап ­  ­ҐЄ®в®аго ЇаЁ¬ЁвЁў­®бвм( бЄ®Ў®Є,
§ а § , ¬­®Ј® Ї«®¤Ёв,   бЁ¬ў®«м­л© 'гЇа®бвЁвҐ«м' бгйҐбвўҐ­­® ¤«Ё­­ҐҐ ;).
„ ©, ¤г¬ о, «о¤џ¬ Ї®¤ ао - ¬®¦Ґв, ЇаЁЈ®¤Ёвбп Є®¬г ;-D.

   Regards,
                        Alexey
                        aka alex@pd.spb.su

  Enough! or Too much.

--- Beta5+
 * Origin: Hollow Hills (FidoNet 2:5030/87.55)



